# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_gallery.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gallery(object):
    def setupUi(self, Gallery):
        Gallery.setObjectName("Gallery")
        Gallery.resize(709, 426)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Gallery)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Gallery)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(40, 40))
        self.frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grid_actions_layout = QtWidgets.QHBoxLayout()
        self.grid_actions_layout.setObjectName("grid_actions_layout")
        self.horizontalLayout_2.addLayout(self.grid_actions_layout)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(Gallery)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.center_widget = QtWidgets.QWidget()
        self.center_widget.setGeometry(QtCore.QRect(0, 0, 707, 340))
        self.center_widget.setObjectName("center_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.center_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.center_widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("colorEditor")
        self.verticalLayout_4.addWidget(self.label)
        self.scrollArea.setWidget(self.center_widget)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(Gallery)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_first_page = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_first_page.sizePolicy().hasHeightForWidth())
        self.btn_first_page.setSizePolicy(sizePolicy)
        self.btn_first_page.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_first_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_first_page.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_first_page.setIcon(icon)
        self.btn_first_page.setIconSize(QtCore.QSize(18, 18))
        self.btn_first_page.setObjectName("btn_first_page")
        self.horizontalLayout.addWidget(self.btn_first_page)
        self.btn_prev_page = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prev_page.sizePolicy().hasHeightForWidth())
        self.btn_prev_page.setSizePolicy(sizePolicy)
        self.btn_prev_page.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_prev_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_prev_page.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev_page.setIcon(icon1)
        self.btn_prev_page.setIconSize(QtCore.QSize(18, 18))
        self.btn_prev_page.setObjectName("btn_prev_page")
        self.horizontalLayout.addWidget(self.btn_prev_page)
        self.line_2 = QtWidgets.QFrame(self.frame_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lbl_current_page = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_current_page.sizePolicy().hasHeightForWidth())
        self.lbl_current_page.setSizePolicy(sizePolicy)
        self.lbl_current_page.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.lbl_current_page.setFont(font)
        self.lbl_current_page.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_current_page.setObjectName("lbl_current_page")
        self.horizontalLayout.addWidget(self.lbl_current_page)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lbl_total_pages = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_total_pages.sizePolicy().hasHeightForWidth())
        self.lbl_total_pages.setSizePolicy(sizePolicy)
        self.lbl_total_pages.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.lbl_total_pages.setFont(font)
        self.lbl_total_pages.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_pages.setObjectName("lbl_total_pages")
        self.horizontalLayout.addWidget(self.lbl_total_pages)
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.btn_next_page = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next_page.sizePolicy().hasHeightForWidth())
        self.btn_next_page.setSizePolicy(sizePolicy)
        self.btn_next_page.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_next_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next_page.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_page.setIcon(icon2)
        self.btn_next_page.setIconSize(QtCore.QSize(18, 18))
        self.btn_next_page.setObjectName("btn_next_page")
        self.horizontalLayout.addWidget(self.btn_next_page)
        self.btn_last_page = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_last_page.sizePolicy().hasHeightForWidth())
        self.btn_last_page.setSizePolicy(sizePolicy)
        self.btn_last_page.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_last_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_last_page.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_last_page.setIcon(icon3)
        self.btn_last_page.setIconSize(QtCore.QSize(18, 18))
        self.btn_last_page.setObjectName("btn_last_page")
        self.horizontalLayout.addWidget(self.btn_last_page)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_2)

        self.retranslateUi(Gallery)
        QtCore.QMetaObject.connectSlotsByName(Gallery)

    def retranslateUi(self, Gallery):
        _translate = QtCore.QCoreApplication.translate
        Gallery.setWindowTitle(_translate("Gallery", "Form"))
        self.label.setText(_translate("Gallery", "Drag and Drop your images/videos"))
        self.label_3.setText(_translate("Gallery", "Page"))
        self.lbl_current_page.setText(_translate("Gallery", "0"))
        self.label_2.setText(_translate("Gallery", "of "))
        self.lbl_total_pages.setText(_translate("Gallery", "0"))
